# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: stream.proto for package 'stream'

require 'grpc'
require 'stream_pb'

module Stream
  module AudioStreamer
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'stream.AudioStreamer'

      rpc :Stream, ::Stream::SongInfoRequest, stream(::Stream::AudioResponse)
    end

    Stub = Service.rpc_stub_class
  end
  module SongSearcher
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'stream.SongSearcher'

      rpc :Search, ::Stream::SongSearchRequest, ::Stream::SongInfoResponse
    end

    Stub = Service.rpc_stub_class
  end
end
